# Generated by Django 4.2.7 on 2024-03-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя птицы')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет птицы')),
                ('like', models.IntegerField(default=0, verbose_name='Лайки, поставленные птице')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение птицы')),
            ],
        ),
    ]
